Feature/board
devv-up/backend pull request #11
Opened 2020-02-29 12:32 UTC by yimsb01

I added a Board application and need customised user model.
As you could find from my commit messages,
Photo application is also needed for both User application and Board application.
If there are not any problem, I would like to start creating features of basic board which don't have photos yet.

Let me know anytime if I am doing something wrong.

2020-02-29 19:43 UTC, choitaehoon1998 approved these changes

2020-03-01 13:02 UTC, hyeonjames requested changes

2020-03-01 13:02 UTC, hyeonjames commented on .gitignore
> +# End of https://www.gitignore.io/api/django,python,pycharm,visualstudiocode
이거 맨 끝줄에다가 넣어주시고, 추가한 부분에 대해서는 코멘트 정도만 해주세요

2020-03-01 13:02 UTC, hyeonjames commented on board/admin.py
> +from django.contrib import admin  # noqa: 401
noqa는 필요 없죠, 밑에서 사용하고 있으니까 오류 안날꺼에요. 빼주세요

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +from django.db import models  # noqa: F401
마찬가지로 밑에서 사용하고 있으니 noqa는 필요가 없어요. 빼주세여

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    meeting_location = models.CharField(max_length=75)
앞에 접두사 `meeting`은 필요가 없어요. 그냥 `location`, `capacity`, `date` 등으로 만들어주세요.
(단순히 meeting 을 위한 게 아니니까요)

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    board_tags = models.ManyToManyField('Board')
잠깐 이게 왜 여기 있죠? 반대인거 같은데요, 게시글 쪽에 `tags`를 가지고 있어야 되는 형태여야 될거 같아요

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    meeting_location = models.CharField(max_length=75)
아, 추가로 주소가 75자는 너무 짧은 듯요? 적당히 255자로 하는게 좋겠어요.
마찬가지로 `title` 같은 것도 너무 짧아요.

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    author = models.ForeignKey(User, on_delete=models.CASCADE)
모델 속성들을 보고나니까 이건 `Board`라고 볼 수가 없네요. 이름을 바꾸셔야 될거 같아요. 엄청 헷갈리네요
`Board`라는 건 "게시판"을 의미하는 거고, 이 속성들은 "게시글" 이라고 봐야 될거 같은데요..

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
`user`보다는 `author`가 어울리겠네요

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
`on_delete`를 `CASCADE`로 잡는 것은 잘 생각해 봐야 되는 문제에요. 이 뜻은 사용자가 삭제되면 코멘트도 같이 삭제된다는 뜻인데, 코멘트 같은 것들은 삭제 안하는게 낫습니다. 기록에 남지가 않아서 추적하기가 힘들어요

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    parent_comment = models.ForeignKey('self', on_delete=models.SET_NULL, null=True)
이런 문제가 있어요.
A라는 사람이 코멘트를 달고 B 라는 사람이 그 코멘트에 답글을 달았어요.
A라는 사람이 코멘트를 삭제 했어요. 그럼 B라는 사람이 남긴 코멘트가 parent가 NULL이 되면서, 그 답글은 답글이 아닌 그냥 댓글로 인식이 될거에요

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    category = models.ForeignKey('Category', on_delete=models.CASCADE)
`CASCADE` 노노, 이거 역시 카테고리가 사라졌다고 게시글이 사라지는 건 별로 좋지가 않아요.;; 기록상 남기는 게 좋아요.

2020-03-01 13:02 UTC, hyeonjames commented on board/models.py
> +    title = models.CharField(max_length=30, db_index=True)
title처럼 문자열이고 꽤나 긴 형태로 들어가는 경우는 인덱스를 만드는게 좋은 생각인지 모르겠어요.
 `db_index` 는 추후에 생각해보고 넣는걸로 하죠.

2020-03-01 14:54 UTC, yimsb01 commented on .gitignore
> +# End of https://www.gitignore.io/api/django,python,pycharm,visualstudiocode
제일 밑으로 옮기고 주석으로 pycharm 관련 세팅파일들이라고 적었습니다.

2020-03-01 14:54 UTC, yimsb01 commented on board/admin.py
> +from django.contrib import admin  # noqa: 401
넵

2020-03-01 14:54 UTC, yimsb01 commented on board/models.py
> +from django.db import models  # noqa: F401
넵

2020-03-01 14:55 UTC, yimsb01 commented on board/models.py
> +    meeting_location = models.CharField(max_length=75)
접두사 전부 빼고 주소는 255자로, title은 50자로 늘렸습니다.

2020-03-01 14:55 UTC, yimsb01 commented on board/models.py
> +    board_tags = models.ManyToManyField('Board')
board_tags의 이름을 post_tags로 바꾸고 Post 모델쪽으로 이동시켰습니다.

2020-03-01 14:55 UTC, yimsb01 commented on board/models.py
> +    author = models.ForeignKey(User, on_delete=models.CASCADE)
넵 Post로 바꿨습니다.

2020-03-01 14:56 UTC, yimsb01 commented on board/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
author로 바꾸고 on_delete를 전부 PROTECT로 바꿨습니다.
그리고 중요 모델들에 대해서는 삭제가 아닌 비활성화로 바꾸기 위해 is_active 필드를 추가하고 디폴트 값을 False로 바꿨습니다.

2020-03-01 14:56 UTC, yimsb01 commented on board/models.py
> +    parent_comment = models.ForeignKey('self', on_delete=models.SET_NULL, null=True)
이를 방지 하기 위해 코멘트의 삭제를 못하게 PROTECT로 바꿨습니다

2020-03-01 14:56 UTC, yimsb01 commented on board/models.py
> +    category = models.ForeignKey('Category', on_delete=models.CASCADE)
넵

2020-03-01 14:57 UTC, yimsb01 commented on board/models.py
> +    title = models.CharField(max_length=30, db_index=True)
넵 db_index를 제거했습니다.

2020-03-02 11:18 UTC, hyeonjames requested changes
develop rebase 한번 해주세요~

2020-03-02 11:18 UTC, hyeonjames commented on post/models.py
> +    post_tags = models.ManyToManyField('Post')
그냥 ‘tags’ 가 맞을듯여

2020-03-02 11:18 UTC, hyeonjames commented on post/models.py
> +        return self.title
str같은 경우 로그를 위해서 많이 쓰여요. 그런데 title 은 충분히 중복될 수 있으니 title만 넣는 건 좋지 않을 듯 하네요.
`f'#{self.id} : {self.title}'` 이런식으로 로그를 써도 찾아볼 수 있는 내용을 쓰는게 좋겠어요.

2020-03-02 11:18 UTC, hyeonjames commented on post/models.py
> +        return self.content
`Post` 쪽과 마찬가지로 처리해주세요,
단 `Comment`의 경우 내용이 지나치게 길어질 수 있어요.
따라서 Comment id 정도만 넣는게 좋겠네요

2020-03-02 15:28 UTC, yimsb01 commented on post/models.py
> +    post_tags = models.ManyToManyField('Post')
넵 tags로 수정하였습니다.

2020-03-02 15:30 UTC, yimsb01 commented on post/models.py
> +        return self.title
post, category, tag 전부 해당 방식으로 수정하였습니다.

2020-03-02 15:30 UTC, yimsb01 commented on post/models.py
> +        return self.content
넵

2020-03-02 16:27 UTC, hyeonjames requested changes

2020-03-02 16:27 UTC, hyeonjames commented on post/models.py
> +        return f'#{self.id} : {self.title}'
‘Tag’ 랑 ‘Category’ 쪽은 id 표시가 필요없죠. title이 unique인데
똑같이 타이틀로 줘버리면 어떤게 Post이고 어떤게 Tag인지 모르는데.. 똑같이 만들어 버리시면 구별을 못해요
Comment 처럼 ‘Category’, ‘Tag’, ‘Post’ 쪽도 표시를 넣어주세요

2020-03-02 16:36 UTC, hyeonjames commented on post/models.py
> +        return f'#{self.id} : {self.title}'
차라리, 이런식으로 표시하는 게 나을 듯요.
‘Post(id=..,title=‘’)’
Category랑 Tag는 id가 필요 없으니 title만 넣구요

2020-03-02 16:37 UTC, hyeonjames requested changes

2020-03-02 16:37 UTC, hyeonjames commented on post/models.py
> +    tags = models.ManyToManyField('Post')
Post -> Tag

2020-03-03 01:10 UTC, yimsb01 commented on post/models.py
> +        return f'#{self.id} : {self.title}'
넹 그게 좋을 것 같습니다.

2020-03-03 01:10 UTC, yimsb01 commented on post/models.py
> +    tags = models.ManyToManyField('Post')
수정했습니다

2020-03-03 02:48 UTC, hyeonjames requested changes

2020-03-03 02:48 UTC, hyeonjames commented on post/models.py
> +    author = models.ForeignKey(User, on_delete=models.PROTECT)
‘CASCADE’ 를 쓸때는 잘 생각해봐야 한다고 했지만 다 PROTECT로 박으란 소린 아닌데 ;;
이렇게 하면 무결성이 떨어져요
Comment 의 Parent_comment 말고는 SET_NULL 해도 되요..

2020-03-03 03:32 UTC, yimsb01 commented on post/models.py
> +    author = models.ForeignKey(User, on_delete=models.PROTECT)
데이터 무결성...그렇군요! 수정했습니다.

2020-03-03 05:26 UTC, hyeonjames approved these changes

2020-03-03 05:48 UTC, merged