Update project settings
devv-up/backend pull request #12
Opened 2020-03-01 14:19 UTC by choitaehoon1998

Change requirements.txt to use libary for this project
Change settings.py for this project

2020-03-01 14:41 UTC, yimsb01 commented on dev_up/settings.py
> +        'ENGINE': 'django.db.backends.postgresql_psycopg2',
젠킨스를 통과시키기 위해서 아직은 postgres로 설정하는 것보다 sqlite3로 놔두는게 좋을듯 합니다.

2020-03-01 14:42 UTC, yimsb01 commented on dev_up/settings.py
> +    'rest_framework',
이미 알고 있겠지만 이 부분은 feature/settings에서 추가하는게 나아보이네요.

2020-03-01 14:43 UTC, hyeonjames commented on dev_up/settings.py
> +        'ENGINE': 'django.db.backends.postgresql_psycopg2',
아녀 젠킨스는 jenkins.py 로 설정하고 있어서 상관없을 것 같아요. jenkins.py에서 덮어 씌워요

2020-03-01 14:43 UTC, yimsb01 commented on dev_up/settings.py
> +SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
환경변수에 관한것은 일단 젠킨스랑 도커 세팅하실 때 바꾸시게 일단은 그냥 두는게 좋을것 같습니다.

2020-03-01 14:46 UTC, choitaehoon1998 commented on dev_up/settings.py
> +    'rest_framework',
어? 여기가 feature/settings인데요?

2020-03-01 14:47 UTC, elliotyim reviewed
그리고 또 하나의 테스트 코멘트입니다.

2020-03-01 14:47 UTC, yimsb01 commented on dev_up/settings.py
> +DEBUG = os.environ['DJANGO_DEBUG']
리뷰테스트를 위한 코멘트입니다.

2020-03-01 14:48 UTC, yimsb01 commented on dev_up/settings.py
> +DEBUG = os.environ['DJANGO_DEBUG']
테스트 코멘트 하나 더

2020-03-01 14:52 UTC, yimsb01 commented on dev_up/settings.py
> +    'rest_framework',
잘못봤습니다 죄송합니다.

2020-03-01 14:56 UTC, hyeonjames commented on dev_up/settings.py
> +    'rest_framework',
settings.py는 이 pr에서 수정하는 게 맞는 것 같네요. 제꺼에서 뺄게요.
단, 제꺼 참조해서 수정해주세요. 이렇게 하면 오류 날것 같아요

2020-03-01 14:59 UTC, choitaehoon1998 commented on dev_up/settings.py
> +    'rest_framework',
#10 을 참고해서 수정하면 될까요?

2020-03-01 15:01 UTC, hyeonjames commented on dev_up/settings.py
> +    'rest_framework',
넵

2020-03-02 11:13 UTC, hyeonjames requested changes
develop rebase 한번 해주세요~

2020-03-02 11:13 UTC, hyeonjames commented on dev_up/settings.py
> +        'NAME': 'devupdb',
이부분도 `os.environ` 쓰셔야 될거 같네요~ ( 밑 부분도 )

2020-03-02 11:47 UTC, choitaehoon1998 commented on dev_up/settings.py
> +        'NAME': 'devupdb',
수정했읍니다 그리고 develop 리베이스도 했습니다

2020-03-02 11:53 UTC, hyeonjames commented on dev_up/settings.py
> +        'HOST': os.environ['POSTGRESQL_HOST'],
`environ` 는 `.get`으로 접근 해주세요
안그러면 mypy 오류나요.

2020-03-02 12:25 UTC, choitaehoon1998 commented on dev_up/settings.py
> +        'HOST': os.environ['POSTGRESQL_HOST'],
넵 수정 완료했습니다
os.environ.get("postgresql_host")이런식으로요!

2020-03-02 16:41 UTC, hyeonjames requested changes

2020-03-02 16:41 UTC, hyeonjames commented on Dockerfile
> -FROM python:3.8
Rebase 잘못 하신거 같네요.
원래 여기에 이 내용이 뜨면 안되요..

2020-03-03 04:18 UTC, elliotyim requested changes

2020-03-03 04:18 UTC, elliotyim commented on dev_up/jenkins.py
> +from dev_up.settings import BASE_DIR
위에 *로 import 했으니까 BASE_DIR을 따로 중복해서 쓸 필요는 없지 않을까요?
아니면 BASE_DIR만 남긴다던지 하는게 나을 것 같아요.

2020-03-03 05:22 UTC, hyeonjames approved these changes

2020-03-03 05:27 UTC, merged