Feature/settings - Add url settings for getting the swagger ready to use
devv-up/backend pull request #24
Opened 2020-03-09 18:32 UTC by yimsb01

drf-yasg를 사용하는 데 있어서 누락된 세팅을 추가합니다.
이 세팅을 추가하고 난 뒤에 urls.py에 연결되어있는 페이지(ex: localhost:8000/swagger/)에 들어가면 사용가능한 api 정보를 전부 볼 수 있습니다.
(drf를 사용하여 api를 만들었다면 자동으로 api를 문서로 만들어줍니다.)

기본적인 설명은 모듈 내에서 docstring으로 작성해두면 api 설명란에 자동으로 추가해줍니다.
decorator를 사용하여 api에 추가로 상세한 정보를 제공하려면 아래의 링크를 참조하세요.
Link: https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#support-for-serializermethodfield

2020-03-14 14:01 UTC, hyeonjames requested changes

2020-03-14 14:01 UTC, hyeonjames commented on dev_up/urls.py
> +from rest_framework import permissions  # type: ignore
djangorestframework-stubs 넣고, `# type: ignore` 지워주세요

2020-03-14 14:01 UTC, hyeonjames commented on requirements.txt
>  djangorestframework
이거 버전 명시하는게 좋을 것 같아요

2020-03-14 14:01 UTC, hyeonjames commented on requirements.txt
> +psycopg2
마찬가지로 버전 명시 하는게 좋겠어요ㅕ

2020-03-14 15:14 UTC, yimsb01 commented on dev_up/urls.py
> +from rest_framework import permissions  # type: ignore
우선 djangorestframework-stubs는 다른 곳들에도 사용될 것 같아서
requirements.txt에 추가했습니다.
또한 permissions는 밑의 permission_classes의 값으로서 사용되고 있었지만
이는 default 값으로 지정되어 있기에 중복되기도 하고 mypy 오류를 일으키기에 제거하였습니다.
따라서 rest_framework의 permissions 또한 필요없을 것이라 판단되어 제거하였습니다.

2020-03-14 15:14 UTC, yimsb01 commented on requirements.txt
>  djangorestframework
넵 수정하였습니다.

2020-03-14 15:14 UTC, yimsb01 commented on requirements.txt
> +psycopg2
넵 수정하였습니다.

2020-03-15 11:16 UTC, hyeonjames approved these changes
수고하셨어요 ~ 👍

2020-03-15 18:55 UTC, choitaehoon1998 commented
수고하셨습니당 👍

2020-03-15 18:56 UTC, choitaehoon1998 approved these changes

2020-03-16 01:18 UTC, merged