소셜 로그인 기능을 추가하였습니다
devv-up/backend pull request #26
Opened 2020-03-15 19:38 UTC by choitaehoon1998

DB에 따로 google,github Oauth클라이언트 아이디와 비밀키를 추가해주어야합니다 , 제꺼에서는 될껀데 딴거에서는 안될거같습니다

2020-03-15 20:12 UTC, hyeonjames commented
> DB에 따로 google,github Oauth클라이언트 아이디와 비밀키를 추가해주어야합니다 , 제꺼에서는 될껀데 딴거에서는 안될거같습니다

DB에 굳이 넣어야 하는 이유가 있나요? 환경변수로 처리하면 될 텐데, 별 다른 이유 없는 이상은 납득하기가 어렵네요

2020-03-15 20:14 UTC, hyeonjames requested changes

2020-03-15 20:14 UTC, hyeonjames commented on dev_up/settings.py
> +            'read:org',
저희가 `repo`와 `read:org` 권한이 꼭 필요할까요? `user` 만 있어도 될 것 같은데 그 외에 사용 용도가 있나요?

2020-03-15 20:25 UTC, choitaehoon1998 commented on dev_up/settings.py
> +            'read:org',
아뇨 필요없을것 같습니다 저의 착오입니다

2020-03-15 20:27 UTC, choitaehoon1998 commented on dev_up/settings.py
> +            'read:org',
그리고 지금 젠킨스에서 오류나는 부분때문에 setup.cfg에 allauth.* 을 추가하였는데 feature/setting에 올렸습니다

2020-03-15 20:40 UTC, choitaehoon1998 commented on dev_up/settings.py
> +            'read:org',
그리고 제가 맨처음에 allauth를 시작할때는 settings.py 에서 클라이언트 id와 키를 저장하는줄 알았는데 인터넷에서 예시를 찾고 , django-allauth 예시를 살펴보니 db에 클라이언트 id 와 키를 저장하길래 이것이 좀더 일반적인 방법이구나 생각하며 db에 저장했던것입니다

2020-03-15 20:53 UTC, hyeonjames commented on dev_up/settings.py
> +            'read:org',
DB 특정 값에 의존이 생기면 관리가 어렵습니다. 단순히 인터넷에서 그 글 봤다고 해서 그게 일반적이라고 보기는 힘들어요.
django-allauth document에는 settings에 넣고 있는 걸로 보이구요.
https://django-allauth.readthedocs.io/en/latest/installation.html

2020-03-15 21:08 UTC, choitaehoon1998 commented on dev_up/settings.py
> +            'read:org',
수정하였습니다 ... mypy 에서 오류나는 부분은 setup.cfg 에 추가하였는데 (feature/settings에 올렸는데 왜인지 여기에다가도 올려야 할것만 같은 기분이군요)

2020-03-15 21:33 UTC, hyeonjames requested changes

2020-03-15 21:33 UTC, hyeonjames commented on dev_up/settings.py
> +            'client_id': os.environ.get("Google_oauth_client_id", 'abcdegfddgffgg'),
기본 값은 그냥 빈칸으로 하는게 나을 것 같아요

2020-03-15 21:33 UTC, hyeonjames commented on post/migrations/0001_initial.py
> +from django.db import migrations, models
migrations 폴더에 __init__.py 빼고 다 지워주세요;

2020-03-15 21:37 UTC, hyeonjames commented on post/migrations/0001_initial.py
> +from django.db import migrations, models
Django migration 파일의 경우 마이그레이션 관리에 대한 얘기가 되고 나서 어떻게 할지 결정하는 걸로 하고, 그 전에는 소스코드에 포함하지 말아주세요.

2020-03-15 22:14 UTC, choitaehoon1998 commented on post/migrations/0001_initial.py
> +from django.db import migrations, models
제가 잘못 올린거같습니다 잠시후에 지우고 다시 올리겠습니다

2020-03-15 22:15 UTC, choitaehoon1998 commented on dev_up/settings.py
> +            'client_id': os.environ.get("Google_oauth_client_id", 'abcdegfddgffgg'),
Abcde....이런식으로 설정되어있는부분 말씀하시는거죠??
Os.env.get(a,””)이런식으로 수정하면 괜찮을까요

2020-03-16 09:27 UTC, hyeonjames requested changes

2020-03-16 09:27 UTC, hyeonjames commented on dev_up/settings.py
> +            'client_id': os.environ.get("Google_oauth_client_id", ''),
다른 환경변수들은 다 대문자로 이루어 져있는데, 여기만 소문자가 섞여있으면 이상한것 같은데요, 똑같이 맞춰주세요.

2020-03-16 09:27 UTC, hyeonjames commented on dev_up/urls.py
> +from django.urls import include, path
저번과 마찬가지로 rebase 잘못 하신것 같아요. 이 내용은 여기 있으면 안되요.

2020-03-16 09:34 UTC, choitaehoon1998 commented on dev_up/urls.py
> +from django.urls import include, path
저번에는 뭐가 문제인지 몰랐지만 이번에는 뭐가 문제인줄알겠습니다 
rebase 를 실행해서 conflict 나는부분이 5개 있다면 1/5 에서부 터 django.url import include,path 를 추가해줬었는데 제가 추가 해줬어야하는시점은 rebase 가 끝난 이후 였군요 !!

2020-03-16 15:01 UTC, choitaehoon1998 commented on dev_up/settings.py
> +            'client_id': os.environ.get("Google_oauth_client_id", ''),
수정하였습니다

2020-03-16 15:01 UTC, choitaehoon1998 commented on dev_up/urls.py
> +from django.urls import include, path
수정하였습니다

2020-03-17 02:48 UTC, yimsb01 commented on dev_up/urls.py
> +    path('user/', include('user.routers')),
이거 보고 생각난건데, 제 쪽도 path를 ""에서 "post-api/" 같은걸로 바꿔야겠네요.
"user"도 "user-api/" 등으로 바꾸는거에 대해서 어떻게 생각하시나요?
@choitaehoon1998 @hyeonjames

2020-03-17 03:19 UTC, hyeonjames commented on dev_up/urls.py
> +    path('user/', include('user.routers')),
저희 url 자체가 이미 api.dev-up.kr/ 로 하기로 했었는데, `-api`가 들어가면 이상할 것 같은데요.?

2020-03-17 03:24 UTC, hyeonjames approved these changes
수고하셨습니다~ 👍

2020-03-17 03:26 UTC, hyeonjames commented on dev_up/urls.py
> +    path('user/', include('user.routers')),
사실 만약 안들어가더라도 `post-api` `user-api` 같은 이름은 별로 좋게 느껴지지가 않아요, 보통 간단하게 쓰고, 앞에 api 와 버전 명을 붙이는게 일반적인 걸로 알고 있어요. `/api/user/` `/api/v1/user`

2020-03-17 03:52 UTC, yimsb01 commented on dev_up/urls.py
> +    path('user/', include('user.routers')),
아 그렇네요.. 이미 api가 들어가는구나
사실 저기서 api를 붙인 이유가 만약 post관련 api를 호출하게 되면 링크가

GET /post/posts/3
처럼 되어서 중복되는 문제가 생겨버려서 였는데, 다른 방법을 생각해보겠습니다.

2020-03-17 03:53 UTC, elliotyim approved these changes
고생하셨습니다

2020-03-17 04:23 UTC, merged