feature/user login,logout
devv-up/backend pull request #36
Opened 2020-04-21 17:17 UTC by choitaehoon1998

2020-04-25 09:08 UTC, hyeonjames requested changes

2020-04-25 09:08 UTC, hyeonjames commented on setup.cfg
> +[mypy-numpy.*,setuptools.*,pytest.*,django.*,ruamel.*,drf_yasg.*,allauth.*,rest_framework_jwt.*,rest_auth.*,rest_framework.*]
rest_framework 는 왜 다시 들어간걸까요?

2020-04-25 09:08 UTC, hyeonjames commented on user/social.py
> +    callback_url = "http://127.0.0.1:8000/user/accounts/github/login/callback/"
`http://127.0.0.1:8000` -> 이부분 default가 있는 환경 변수 값으로 설정해주세요.

2020-04-25 09:08 UTC, hyeonjames commented on user/routers.py
> +    path('api-token-auth/', obtain_jwt_token),
이미 api서버기 때문에 api- 부분은 불필요합니다.
url은 간단한 형태로 넣어주세요
`auth/`
`auth/refresh`
`auth/verify`
`auth/social/registration`
`auth/social/github`
`auth/social/google`

2020-04-25 09:39 UTC, yimsb01 commented on dev_up/settings.py
> +EMAIL_PORT = 587
smtp host랑 port는 다른 걸 쓸 수도 있으니까 환경변수로 바꿔주세요

2020-04-25 14:18 UTC, choitaehoon1998 commented on setup.cfg
> +[mypy-numpy.*,setuptools.*,pytest.*,django.*,ruamel.*,drf_yasg.*,allauth.*,rest_framework_jwt.*,rest_auth.*,rest_framework.*]
![rest_framework](https://user-images.githubusercontent.com/51841238/80281934-8b70a880-8749-11ea-8487-268c05ac501d.JPG)
seup.cfg 의 말씀 하신부분을 빼면 위의 첨부한 사진과같은 오류가 발생하네요 .....
제가 저번에도 rest_framework 를 추가한적이있나 찾고 있는데 잘안보이네요 ㅇㅅㅇ

2020-04-25 14:51 UTC, yimsb01 commented on setup.cfg
> +[mypy-numpy.*,setuptools.*,pytest.*,django.*,ruamel.*,drf_yasg.*,allauth.*,rest_framework_jwt.*,rest_auth.*,rest_framework.*]
> ![rest_framework](https://user-images.githubusercontent.com/51841238/80281934-8b70a880-8749-11ea-8487-268c05ac501d.JPG)
> seup.cfg 의 말씀 하신부분을 빼면 위의 첨부한 사진과같은 오류가 발생하네요 .....
> 제가 저번에도 rest_framework 를 추가한적이있나 찾고 있는데 잘안보이네요 ㅇㅅㅇ

이거 18번 줄의 re_path는 rest_framework.compat쪽 말고 django.urls의 re_path 써도 될겁니다. 라이브러리 확인해보니까 애초에 django.urls거 가져와서 쓰네요.

그리고 미니콘다 dev_up에 djangorestframework-stubs==1.1.0가 있는지 확인해보세요. featrue/user 브랜치의 requirements.txt에는 있는데 설치가 안된듯

2020-04-25 16:13 UTC, choitaehoon1998 commented on setup.cfg
> +[mypy-numpy.*,setuptools.*,pytest.*,django.*,ruamel.*,drf_yasg.*,allauth.*,rest_framework_jwt.*,rest_auth.*,rest_framework.*]
오 ! 감사합니다 !!!

2020-04-26 05:58 UTC, yimsb01 commented on user/routers.py
> +    path('api-token-auth/', obtain_jwt_token),
아 그리고 사소한거지만 verify보다 자원은 명사형인 verification이 낫습니다.

2020-04-28 14:32 UTC, elliotyim requested changes
저 세개 정도만 고치면 다른 부분은 괜찮을듯?
~~근데 registration 할 때 AttributeError: 'tuple' object has no attribute 'rsplit' 에러 나던데 제가 대체 뭘 잘못했는지 모르겠네요 ㄷㄷ;; 일단은 구글링 해볼게요~~

2020-04-28 14:32 UTC, yimsb01 commented on dev_up/settings.py
> +    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=28),
토큰의 경우 탈취 당하면 보안에 취약하기 때문에 Expration_DELTA를 1시간으로,
REFRESH_EXPIRATION_DELTA의 경우 14일로 해주면 좋을 것 같습니다.
참고 링크: https://tansfil.tistory.com/59

2020-04-28 14:32 UTC, yimsb01 commented on dev_up/settings.py
> +EMAIL_HOST = "smtp.gmail.com"
요거 빠뜨리셨네요.
PORT랑 똑같이 환경변수로 바꿔주세요.

2020-04-28 14:32 UTC, yimsb01 commented on dev_up/settings.py
> +LOGIN_REDIRECT_URL = '/'
rest로만 쓰는거면 
- ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL
- ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL
- LOGIN_REDIRECT_URL

얘네 셋은 없어도 되지 않을까요?
어차피 http 요청으로만 전부 이루어지니까요
혹시 얘네 셋이 필수 옵션인가 해서 docs 봤는데
제가 못찾는건지 없네요

2020-04-28 16:05 UTC, choitaehoon1998 commented on dev_up/settings.py
> +LOGIN_REDIRECT_URL = '/'
제가 착각했네요 (ㅜ.ㅜ) 죄송합니다

2020-04-28 16:05 UTC, choitaehoon1998 commented on dev_up/settings.py
> +EMAIL_HOST = "smtp.gmail.com"
넵

2020-04-28 16:05 UTC, choitaehoon1998 commented on dev_up/settings.py
> +    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=28),
넵

2020-04-28 16:05 UTC, choitaehoon1998 commented on dev_up/settings.py
> +EMAIL_PORT = 587
넵

2020-04-28 16:05 UTC, choitaehoon1998 commented on user/routers.py
> +    path('api-token-auth/', obtain_jwt_token),
넵

2020-04-28 16:05 UTC, choitaehoon1998 commented on user/social.py
> +    callback_url = "http://127.0.0.1:8000/user/accounts/github/login/callback/"
넵

2020-04-28 16:27 UTC, hyeonjames requested changes

2020-04-28 16:27 UTC, hyeonjames commented on user/social.py
> +    callback_url = SITE_URL+":/user/accounts/google/login/callback/"
+를 이용한 방법 말고 `f''` 를 이용해주세요.
그리고 앞에 : 들어간거 같네요

2020-04-28 16:27 UTC, hyeonjames commented on user/routers.py
> +    re_path('accounts-rest/registration/account-confirm-email/(?P<key>.+)/$',
이것도 바꿔주셔야져..
`auth/registration/confirm` 같은 형식으루요

2020-04-28 16:27 UTC, hyeonjames commented on user/routers.py
> +    path('token/auth/', obtain_jwt_token),
token에 대한 것도 auth가 맞습니다. 따라서 제일 앞에 auth/를 넣고 auth/token, auth/token/refresh, auth/token/verify
같은 형식이 더 좋을 것 같네요.

2020-04-28 20:31 UTC, choitaehoon1998 commented on user/social.py
> +    callback_url = SITE_URL+":/user/accounts/google/login/callback/"
넵 수정하였습니다 !

2020-04-28 20:31 UTC, choitaehoon1998 commented on user/routers.py
> +    path('token/auth/', obtain_jwt_token),
넵 수정하였습니다 !

2020-04-28 20:39 UTC, choitaehoon1998 commented on user/routers.py
> +    re_path('accounts-rest/registration/account-confirm-email/(?P<key>.+)/$',
re_path로 시작하는 부분이 회원가입을 진행하여 메일을 발송후, 회원인증(?) 쯤 되는 주소입니다 
저의 구글링이 부족한탓인지 주소 자체를 수정하는 방법을 찾지 못하였습니다 ...
저번에 리뷰 해주셨을때 이걸 말씀드렸어야했는데 ... ㅜㅜ 저의 불찰입니다

2020-04-29 07:13 UTC, yimsb01 commented
제가 착각했습니다 죄송합니다.

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL

얘네는 있어야 하네요. 다만 이 리다이렉트 URL이 아마 프론트엔드쪽 로그인 페이지가 되어야 할 것 같긴 하네요.

사실 더 좋은건 쟤네도 없애고, 이메일 확인 페이지를 프론트 엔드쪽에서 만드는게 좋긴 합니다.

2020-05-02 13:32 UTC, elliotyim requested changes
~아 그리고, 현재 jwt로 로그인 할 때 username, email, password 세 개를 요구하니까 그것도 email, password만 요청하도록 바꿔주세요.~

~ACCOUNT_USERNAME_REQUIRED = False
이거 넣어주면 될겁니다.~

로그인이 아니라 회원가입이네요. 무시해주세요.

2020-05-02 13:32 UTC, yimsb01 commented on user/routers.py
> +    path('auth/google/connect', GoogleConnect.as_view(), name='google_connect'),
connect가 어디에 쓰이는지는 모르겠지만, 기본적으로 auth/github/으로 회원가입 로그인 다 해결되니까 지워주세요.
auth/github/에 access_token 넣고 요청 보냈을 때 아이디가 없으면 회원가입을 한 다음에 유저 정보와 토큰을 반환하고,
아이디가 이미 있으면 해당 유저정보와 토큰을 반환합니다.

2020-05-02 13:32 UTC, yimsb01 commented on user/social.py
> +    client_class = OAuth2Client
요기도 마찬가지로 지워주세요

2020-05-02 14:17 UTC, yimsb01 commented on user/routers.py
> +    re_path('accounts-rest/registration/account-confirm-email/(?P<key>.+)/$',
https://medium.com/@blakeyang22/django-signup-with-activation-email-via-api-7384e6766710

이 링크의 2. Contents for templates 항목 참고하세요.

2020-05-04 09:19 UTC, elliotyim approved these changes
user/routers.py에서 관련 있는 애들끼리만 읽기 좋게 정리해서 묶어 주시면
제 리뷰는 끝난 것 같습니다.
수고하셨습니다 :)

accounts path명 수정, 유저 등록 확인 메일의 레이아웃 그리고 User 모델에서 verification Key 필드랑 is verified 필드는 안쓰니까 빼는 것은 후속 PR로 다시 작업하시고 내일 취합은 여기까지 하는게 좋을 것 같습니다.
하지만 모델은 함부로 건드는게 아니라고 하니, 위의 두 필드에 대한 부분은 회의 때 다시 이야기 나눠보시죠.

2020-05-24 10:18 UTC, hyeonjames approved these changes
수고하셨습니다~

2020-05-25 03:20 UTC, merged