Fix test errors related with authorization
devv-up/backend pull request #41
Opened 2020-05-25 03:24 UTC by yimsb01

JWT를 적용하고 난 뒤 모든 API 접근에 권한이 필요해져서
테스트 코드에서 401 에러가 나는 부분을 우선적으로 수정했습니다.

2020-05-25 03:35 UTC, choitaehoon1998 approved these changes

2020-05-25 23:09 UTC, yimsb01 commented
테스트 코드에 옵션 두 개가 추가되었습니다.
- HTTP_AUTHORIZATION=token: JWT 토큰을 헤더에 넣는 옵션
- secure=True: 도메인이 HTTPS일 때 테스트 코드가 통과하도록 만드는 옵션

그리고, User에서 Authentication에 JWT가 추가되었기에 Post API가 GET 방식을 제외하고
로그인된 사용자만 API에 접근할 수 있도록 변경했습니다.

2020-05-25 23:11 UTC, elliotyim reviewed
도움!

2020-05-25 23:11 UTC, yimsb01 commented on post/api/post.py
> +        if self.action in ['list', 'retrieve']:
여기서 self.action이 mypy 때문에 현재 클래스에 action이라는 변수가 없다고 나와서
NamedTuple을 상속하려고 했는데 ViewSet을 이미 상속받은 상태라 사용할 수 없다고 나옵니다.
그래서 생성자 쪽에 무의미한 3줄이 추가되었는데, 뭔가 좋은 방법이 없을까요?

2020-05-27 03:46 UTC, hyeonjames commented on post/api/post.py
> +        if self.action in ['list', 'retrieve']:
의도를 알기가 힘든거 같은데, NamedTuple 안써도 기본값은 넣을 수 있어요..
```python
class PostAPI(viewsets.ViewSet):
     action: Optional[str] = None
```
생성자로 action을 설정해주고 싶은 거라면, 그냥 생성자를 넣는게 좋을 것 같아요.

2020-05-27 04:14 UTC, yimsb01 commented on post/api/post.py
> +        if self.action in ['list', 'retrieve']:
> 의도를 알기가 힘든거 같은데, NamedTuple 안써도 기본값은 넣을 수 있어요..
> 
> ```python
> class PostAPI(viewsets.ViewSet):
>      action: Optional[str] = None
> ```
> 
> 생성자로 action을 설정해주고 싶은 거라면, 그냥 생성자를 넣는게 좋을 것 같아요.

헐...그러네요. 난 왜 저렇게 쓴거지?;;
감사합니다!!

2020-05-27 06:21 UTC, hyeonjames requested changes
코멘트 몇개 달았어요~

2020-05-27 06:21 UTC, hyeonjames commented on tests/post/jwt_token.py
> +def get_jwt_token_of(user: User) -> str:
모듈을 설계할 때 위상도 꽤나 중요한데요, 이 모듈은 jwt_token에 관한건데 꼭 post 위치에 있을 이유가 없을 것 같아요.

2020-05-27 06:21 UTC, hyeonjames commented on tests/post/test_comment.py
> +        token = f'JWT {get_jwt_token_of(users[0])}'
token을 왠만하면 fixture로 구현하는게 어떨까요?

2020-05-27 06:22 UTC, yimsb01 commented on tests/post/jwt_token.py
> +def get_jwt_token_of(user: User) -> str:
> 모듈을 설계할 때 위상도 꽤나 중요한데요, 이 모듈은 jwt_token에 관한건데 꼭 post 위치에 있을 이유가 없을 것 같아요.

아 그렇네요 ㄷㄷ;;
다른 API에서 쓸 수도 있으니

2020-05-27 06:28 UTC, yimsb01 commented on tests/post/test_comment.py
> +        token = f'JWT {get_jwt_token_of(users[0])}'
> token을 왠만하면 fixture로 구현하는게 어떨까요?

fixture로 만든다는게 같은 파일 내에서 token을 가져올 수 있게 하는건가요?

토큰이 특정 유저의 정보 (ID, Password)를 가지고 만드는거라서,
만약 글을 쓴 유저만 해당 글을 지울 수 있게 하려면 토큰이 해당 유저가 발급한 것이여야만 해서요.
test 내에서 그 부분을 명시할 필요가 있지 않을까해서 이런 방식으로 만들었습니다.

제가 아직 fixture쪽에 대한 이해도가 부족해서 ㄷㄷ..
fixture로 만들어서 주입받는다면 어떤식으로 하면 될까요?

2020-05-27 06:40 UTC, hyeonjames commented on tests/post/test_comment.py
> +        token = f'JWT {get_jwt_token_of(users[0])}'
어짜피 test 쪽은 어느 유저가 되도 상관이 없을거 같은데, 특정 유저로 제한하는게 아니라면 fixture 로 만들어도 상관이 없을 거에요. 그냥 users fixture 랑 같이 쓰면 되지 않나요?

```python
@pytest.fixture
def token(users):
   return f'JWT {get_jwt_token_of(users[0]}' 
```

2020-05-27 06:42 UTC, yimsb01 commented on tests/post/test_comment.py
> +        token = f'JWT {get_jwt_token_of(users[0])}'
> 어짜피 test 쪽은 어느 유저가 되도 상관이 없을거 같은데, 특정 유저로 제한하는게 아니라면 fixture 로 만들어도 상관이 없을 거에요. 그냥 users fixture 랑 같이 쓰면 되지 않나요?
> 
> ```python
> @pytest.fixture
> def token(users):
>    return f'JWT {get_jwt_token_of(users[0]}' 
> ```

아 그렇네요.
이렇게 변경하겠습니다.

2020-05-27 07:13 UTC, yimsb01 commented
get_jwt_of() 는 아무래도 이 PR에서만 임시로 사용되고 변경되거나 지워질 것 같습니다.
#43 에서 변경된 simplejwt는 다른 방식으로 token을 얻네요.

(참고: https://django-rest-framework-simplejwt.readthedocs.io/en/latest/creating_tokens_manually.html)

2020-05-28 12:16 UTC, hyeonjames approved these changes
수고하셨어요~

2020-05-28 13:02 UTC, choitaehoon1998 approved these changes

2020-05-28 13:33 UTC, merged